export const API_URL = {
  patient: "patients",
  insurance: "insurance",
  medication: "medication",
  signup: "signup",
  login: "login",
  Medical_problems: "condition_allergy",
  profile: "profile",
  medication_list: "master/medication",
  allergy_list: "allergy_list",
  medical_conditions_list: "condition_list",
  visit_history: "encounter",
  immunization: "HL7v2/immunization",
  rotateToken: "totate_token",
  logout: "logout",
  changePassword: "change_password",
  resetPassword: "reset",
  confirmPassword: "confirm",
};
