export const THUNK_NAME = {
  getUser: "user/get",
  verifyStatus: "payment/verify_status",
  retryPayment: "payment/retry",
  updatePaymentStatus: "payment/cancel",
  getUserProfile: "profile/get",
  getPatientDetails: "patient/get",
  updatePatientProfile: "patient/update",
  getMedication: "medication/get",
  updateMedication: "medication/update",
  deleteInsuranceFile: "insurance/file/delete",
  deleteVisitHistoryFile: "visitHistory/file/delete",
  addMedication: "medication/add",
  getInsurance: "insurance/get",
  addInsurance: "insurance/add",
  deleteInsurance: "insurance/delete",
  updateInsurance: "insurance/update",
  getInsuranceById: "insurance/getById",
  getConditonsAndAllergies: "conditonsAndAllergies/get",
  addConditionsAndAllergies: "conditionsAndAllergies/update",
  updateConditionsAndAllergies: "conditionsAndAllergies/update",
  addVisitHistory: "visithistory/add",
  updateVisitHistory: "visithistory/update",
  deleteVisitHistory: "visithistory/delete",
  getVisitHistoryById: "visithistory/getById",
  getVisitHistory: "visitHistory/get",
};

export const SLICE_NAME = {
  userSlice: "user",
  commonSlice: "commonSlice",
  patinetSlice: "patient",
  immunizationSlice: "immunizationSlice",
  appointmentSlice: "appointmentSlice",
  paymentSlice: "paymentSlice",
};
